
use std::io::Error;

fn main() -> Result<(),Error> {
    println!("Hello rusty world!");
    Ok(())
}
